# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'randomforest_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(538, 259)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(581, 259))
        Dialog.setSizeGripEnabled(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(2, 9, 531, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInput = QtWidgets.QWidget()
        self.tabInput.setObjectName("tabInput")
        self.layoutWidget = QtWidgets.QWidget(self.tabInput)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 511, 195))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxVal = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxVal.setObjectName("comboBoxVal")
        self.gridLayout.addWidget(self.comboBoxVal, 7, 0, 1, 1)
        self.labelClassVal = QtWidgets.QLabel(self.layoutWidget)
        self.labelClassVal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClassVal.setObjectName("labelClassVal")
        self.gridLayout.addWidget(self.labelClassVal, 6, 1, 1, 2)
        self.labelVal = QtWidgets.QLabel(self.layoutWidget)
        self.labelVal.setObjectName("labelVal")
        self.gridLayout.addWidget(self.labelVal, 6, 0, 1, 1)
        self.lineEditSegPath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditSegPath.setObjectName("lineEditSegPath")
        self.gridLayout.addWidget(self.lineEditSegPath, 9, 0, 1, 1)
        self.buttonSegPath = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSegPath.setObjectName("buttonSegPath")
        self.gridLayout.addWidget(self.buttonSegPath, 9, 1, 1, 2)
        self.comboBoxTrain = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxTrain.setObjectName("comboBoxTrain")
        self.gridLayout.addWidget(self.comboBoxTrain, 3, 0, 1, 1)
        self.labelClassTrain = QtWidgets.QLabel(self.layoutWidget)
        self.labelClassTrain.setEnabled(True)
        self.labelClassTrain.setSizeIncrement(QtCore.QSize(100, 0))
        self.labelClassTrain.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClassTrain.setObjectName("labelClassTrain")
        self.gridLayout.addWidget(self.labelClassTrain, 0, 1, 1, 2)
        self.labelTrain = QtWidgets.QLabel(self.layoutWidget)
        self.labelTrain.setObjectName("labelTrain")
        self.gridLayout.addWidget(self.labelTrain, 0, 0, 1, 1)
        self.comboBoxFieldVal = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxFieldVal.setObjectName("comboBoxFieldVal")
        self.gridLayout.addWidget(self.comboBoxFieldVal, 7, 1, 1, 2)
        self.comboBoxFieldTrain = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxFieldTrain.setObjectName("comboBoxFieldTrain")
        self.gridLayout.addWidget(self.comboBoxFieldTrain, 3, 1, 1, 2)
        self.labelSegPath = QtWidgets.QLabel(self.layoutWidget)
        self.labelSegPath.setObjectName("labelSegPath")
        self.gridLayout.addWidget(self.labelSegPath, 8, 0, 1, 1)
        self.lineEditPackPath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPackPath.setEnabled(False)
        self.lineEditPackPath.setObjectName("lineEditPackPath")
        self.gridLayout.addWidget(self.lineEditPackPath, 10, 0, 1, 1)
        self.checkBoxPackPath = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxPackPath.setObjectName("checkBoxPackPath")
        self.gridLayout.addWidget(self.checkBoxPackPath, 10, 1, 1, 2)
        self.tabWidget.addTab(self.tabInput, "")
        self.tabParameters = QtWidgets.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.scrollArea = QtWidgets.QScrollArea(self.tabParameters)
        self.scrollArea.setGeometry(QtCore.QRect(9, 9, 511, 181))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -34, 495, 213))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBoxStepEst = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxStepEst.setMinimum(5)
        self.spinBoxStepEst.setMaximum(100)
        self.spinBoxStepEst.setSingleStep(5)
        self.spinBoxStepEst.setProperty("value", 5)
        self.spinBoxStepEst.setObjectName("spinBoxStepEst")
        self.gridLayout_3.addWidget(self.spinBoxStepEst, 3, 5, 1, 1)
        self.spinBoxEndEst = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxEndEst.setMinimum(5)
        self.spinBoxEndEst.setMaximum(100)
        self.spinBoxEndEst.setProperty("value", 30)
        self.spinBoxEndEst.setObjectName("spinBoxEndEst")
        self.gridLayout_3.addWidget(self.spinBoxEndEst, 3, 3, 1, 1)
        self.labelStepEst = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelStepEst.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelStepEst.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStepEst.setObjectName("labelStepEst")
        self.gridLayout_3.addWidget(self.labelStepEst, 3, 4, 1, 1)
        self.radioButtonRegress = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonRegress.setObjectName("radioButtonRegress")
        self.gridLayout_3.addWidget(self.radioButtonRegress, 0, 3, 1, 3)
        self.labelDepth = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelDepth.setObjectName("labelDepth")
        self.gridLayout_3.addWidget(self.labelDepth, 6, 0, 1, 6)
        self.labelEstim = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelEstim.setObjectName("labelEstim")
        self.gridLayout_3.addWidget(self.labelEstim, 2, 0, 1, 5)
        self.labelStartEst = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelStartEst.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStartEst.setObjectName("labelStartEst")
        self.gridLayout_3.addWidget(self.labelStartEst, 3, 0, 1, 1)
        self.spinBoxStartDepth = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxStartDepth.setMinimum(5)
        self.spinBoxStartDepth.setMaximum(100)
        self.spinBoxStartDepth.setObjectName("spinBoxStartDepth")
        self.gridLayout_3.addWidget(self.spinBoxStartDepth, 7, 1, 1, 1)
        self.spinBoxStartEst = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxStartEst.setMinimum(5)
        self.spinBoxStartEst.setMaximum(100)
        self.spinBoxStartEst.setObjectName("spinBoxStartEst")
        self.gridLayout_3.addWidget(self.spinBoxStartEst, 3, 1, 1, 1)
        self.labelEndDepth = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelEndDepth.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEndDepth.setObjectName("labelEndDepth")
        self.gridLayout_3.addWidget(self.labelEndDepth, 7, 2, 1, 1)
        self.labelEndEst = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelEndEst.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEndEst.setObjectName("labelEndEst")
        self.gridLayout_3.addWidget(self.labelEndEst, 3, 2, 1, 1)
        self.labelStartDepth = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelStartDepth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelStartDepth.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStartDepth.setObjectName("labelStartDepth")
        self.gridLayout_3.addWidget(self.labelStartDepth, 7, 0, 1, 1)
        self.labelStepDepth = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelStepDepth.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStepDepth.setObjectName("labelStepDepth")
        self.gridLayout_3.addWidget(self.labelStepDepth, 7, 4, 1, 1)
        self.spinBoxEndDepth = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxEndDepth.setMinimum(5)
        self.spinBoxEndDepth.setMaximum(100)
        self.spinBoxEndDepth.setProperty("value", 30)
        self.spinBoxEndDepth.setObjectName("spinBoxEndDepth")
        self.gridLayout_3.addWidget(self.spinBoxEndDepth, 7, 3, 1, 1)
        self.spinBoxStepDepth = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxStepDepth.setMinimum(5)
        self.spinBoxStepDepth.setMaximum(100)
        self.spinBoxStepDepth.setSingleStep(5)
        self.spinBoxStepDepth.setProperty("value", 5)
        self.spinBoxStepDepth.setObjectName("spinBoxStepDepth")
        self.gridLayout_3.addWidget(self.spinBoxStepDepth, 7, 5, 1, 1)
        self.checkBoxApplyModel = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxApplyModel.setObjectName("checkBoxApplyModel")
        self.gridLayout_3.addWidget(self.checkBoxApplyModel, 9, 0, 1, 3)
        self.radioButtonClass = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonClass.setObjectName("radioButtonClass")
        self.gridLayout_3.addWidget(self.radioButtonClass, 0, 0, 1, 3)
        self.comboBoxCrit = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxCrit.setObjectName("comboBoxCrit")
        self.gridLayout_3.addWidget(self.comboBoxCrit, 8, 4, 1, 2)
        self.labelCrit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelCrit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelCrit.setObjectName("labelCrit")
        self.gridLayout_3.addWidget(self.labelCrit, 8, 0, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tabParameters, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.layoutWidget1 = QtWidgets.QWidget(self.tabOutput)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 511, 213))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonAssessFile = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonAssessFile.setObjectName("buttonAssessFile")
        self.gridLayout_2.addWidget(self.buttonAssessFile, 1, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.buttonCancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonCancel.setObjectName("buttonCancel")
        self.gridLayout_5.addWidget(self.buttonCancel, 0, 0, 1, 1)
        self.buttonRun = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonRun.setObjectName("buttonRun")
        self.gridLayout_5.addWidget(self.buttonRun, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_5.addWidget(self.progressBar, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout_5, 4, 0, 1, 2)
        self.labelRFC = QtWidgets.QLabel(self.layoutWidget1)
        self.labelRFC.setObjectName("labelRFC")
        self.gridLayout_2.addWidget(self.labelRFC, 0, 0, 1, 2)
        self.labelAux = QtWidgets.QLabel(self.layoutWidget1)
        self.labelAux.setText("")
        self.labelAux.setObjectName("labelAux")
        self.gridLayout_2.addWidget(self.labelAux, 5, 0, 1, 2)
        self.labelOutClass = QtWidgets.QLabel(self.layoutWidget1)
        self.labelOutClass.setObjectName("labelOutClass")
        self.gridLayout_2.addWidget(self.labelOutClass, 2, 0, 1, 1)
        self.lineEditAssessFile = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditAssessFile.setObjectName("lineEditAssessFile")
        self.gridLayout_2.addWidget(self.lineEditAssessFile, 1, 0, 1, 1)
        self.lineEditOutModel = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditOutModel.setObjectName("lineEditOutModel")
        self.gridLayout_2.addWidget(self.lineEditOutModel, 3, 0, 1, 1)
        self.buttonOutModel = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonOutModel.setObjectName("buttonOutModel")
        self.gridLayout_2.addWidget(self.buttonOutModel, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tabOutput, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Random Forest"))
        self.labelClassVal.setText(_translate("Dialog", "target field"))
        self.labelVal.setText(_translate("Dialog", "Validation samples (Points)"))
        self.buttonSegPath.setText(_translate("Dialog", "..."))
        self.labelClassTrain.setText(_translate("Dialog", "target field"))
        self.labelTrain.setText(_translate("Dialog", "Training samples (Points)"))
        self.labelSegPath.setText(_translate("Dialog", "Data set"))
        self.checkBoxPackPath.setText(_translate("Dialog", "Packages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInput), _translate("Dialog", "Input"))
        self.labelStepEst.setText(_translate("Dialog", "step"))
        self.radioButtonRegress.setText(_translate("Dialog", "Regression"))
        self.labelDepth.setText(_translate("Dialog", "The maximum depth of the tree"))
        self.labelEstim.setText(_translate("Dialog", "The number of trees in the forest"))
        self.labelStartEst.setText(_translate("Dialog", "start"))
        self.labelEndDepth.setText(_translate("Dialog", "end"))
        self.labelEndEst.setText(_translate("Dialog", "end"))
        self.labelStartDepth.setText(_translate("Dialog", "start"))
        self.labelStepDepth.setText(_translate("Dialog", "step"))
        self.checkBoxApplyModel.setText(_translate("Dialog", "Apply model"))
        self.radioButtonClass.setText(_translate("Dialog", "Classification"))
        self.labelCrit.setText(_translate("Dialog", "The function to measure the quality of a split "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameters), _translate("Dialog", "Parameters"))
        self.buttonAssessFile.setText(_translate("Dialog", "..."))
        self.buttonCancel.setText(_translate("Dialog", "Cancel"))
        self.buttonRun.setText(_translate("Dialog", "Run"))
        self.labelRFC.setText(_translate("Dialog", "Text file"))
        self.labelOutClass.setText(_translate("Dialog", "Vector file"))
        self.buttonOutModel.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), _translate("Dialog", "Output"))

